### ISSUE TITLE
'Insert' button inserts wrong password

### ISSUE THREAD

**Issue by ghost** [eterevsky/passwordgen#3]
I'm not sure how to debug this issue but I can describe it's behaviour.

I visit a website, bring up passwordgen and click 'Insert'. The website tells my the password is incorrect. I then select 'copy' and paste the password, the website accepts my login. This bug happens on multiple websites.

**Comment by eterevsky** [comment]
Sorry, I missed this bug. Does it still happen with the current version? Could you provide at list one URL of login page where this happens?
