### ISSUE TITLE
Suggestion for handling non-US domains

### ISSUE THREAD

**Issue by daemonblade** [eterevsky/passwordgen#6]
If the last component is 2-letters in length, ie: a country-level TLD, it should default to using 3 components instead of just 2; eg trademe.co.nz, amazon.co.uk, commbank.com.au should all use the last 3 components.

Unfortunately, some non-US domains only use 2 components as well; eg airfrance.fr, promod.eu. The only long term solution I can see is extend the Profile attributes to include the number of components to use from the URL. This would allow 3 component non-US sites to use one Profile, and 2 component non-US sites to use another Profile.

**Comment by eterevsky** [comment]
I guess the only correct way is to incorporate into passwordgen the whole list from https://publicsuffix.org/. I'll try to spend some time on passwordgen over the next few days and do it.
